URBANIZACION
```{r}
linkurb="https://github.com/Samanta-Rivera/EPAP2-Proyecto/raw/master/DataUrb.xlsx"
dataurb=import(linkurb)
```
```{r}
dataurb[,c(1,4:7)]=NULL
```

```{r}
dataurb=dataurb[-c(1,3),]
```

```{r}
names(dataurb) = c("Departamento", "Provincia", "Total", "Aurbana", "Arural", "SHombre", "Smujer")
```

```{r}
dataurb=dataurb[-c(1),]
```

```{r}
rownames(dataurb)=NULL
```

```{r}
dataurb[,c(3,6,7)]=NULL
```

INTERNET

```{r}
linkinter="https://github.com/Samanta-Rivera/EPAP2-Proyecto/raw/master/DataInter.xlsx"
datainter=import(linkinter)
```
```{r}
datainter[,c(1,4:7)]=NULL
```

```{r}
names(datainter) = c("Departamento", "Provincia", "Total", "Aurbana", "Arural")
```

```{r}
datainter=datainter[-c(1,3),]
```

```{r}
datainter=datainter[-c(1),]
```

```{r}
rownames(datainter)=NULL
```


```{r}
datainter[,c(1)]=NULL
```

```{r}
datainter[,c(3,4)]=NULL
```

EDUCACION
```{r}
linkedu="https://github.com/Samanta-Rivera/EPAP2-Proyecto/raw/master/DataEdu.xlsx"
dataedu=import(linkedu)
```

```{r}
dataedu[,c(4:7,9:12, 14:17, 19:22)]=NULL
```

```{r}
names(dataedu) = c("Departamento", "Provincia", "EstPrimerSec25años", "EstPrimerEduSup", "EstEduSupNoUni", "TotalEstEduSupUni")
```

```{r}
dataedu=dataedu[-c(1:4),]
```

```{r}
dataedu[,c(1)]=NULL
```

MERGING
```{r}
library(rio)
```

```{r}
UrbInter=merge(dataurb,datainter,by.x='Provincia', by.y='Provincia')
UrbInterEdu=merge(UrbInter,dataedu)
```

