```{r}
library(rio)
link="https://github.com/Samanta-Rivera/EPAP2-Proyecto/raw/master/nombre%20y%20ubigeo%20(1).xlsx"
Ubigeo=import(link)
```

```{r}
library(stringr)
Ubigeo$Ubigeo=str_split(Ubigeo$Codigo , pattern= "#", simplify=T) [,2]
```


```{r}
Ubigeo[,1]=NULL
names(Ubigeo)=c("Provincias","Codigo de Ubigeo")
```


```{r}
Ubigeo$Region=str_split(Ubigeo$Provincias, pattern = ", provincia",simplify = T)[,1]
Ubigeo$Provincia=str_split(Ubigeo$Provincias,pattern = "provincia: ",simplify = T)[,2]
Ubigeo[,1]=NULL
```

```{r}
Ubigeo$Concatenado=paste0(Ubigeo$Region,'-',Ubigeo$Provincia)
Ubigeo[,c(2,3)]=NULL
```

```{r}
Ubigeo[,2]=gsub('á','a',Ubigeo[,2])
Ubigeo[,2]=gsub('é','e',Ubigeo[,2])
Ubigeo[,2]=gsub('í','i',Ubigeo[,2])
Ubigeo[,2]=gsub('ó','o',Ubigeo[,2])
Ubigeo[,2]=gsub('ú','u',Ubigeo[,2])
Ubigeo[,2]=gsub('ñ','n',Ubigeo[,2])
Ubigeo[,2]=gsub('Á','A',Ubigeo[,2])
Ubigeo[,2]=gsub('É','E',Ubigeo[,2])
Ubigeo[,2]=gsub('Í','I',Ubigeo[,2])
Ubigeo[,2]=gsub('Ó','O',Ubigeo[,2])
Ubigeo[,2]=gsub('Ú','U',Ubigeo[,2])
Ubigeo[,2]=gsub('Ñ','N',Ubigeo[,2])
```