URBANIZACION
```{r}
library(rio)
linkurb="https://github.com/Samanta-Rivera/EPAP2-Proyecto/raw/master/DataUrb.xlsx"
dataurb=import(linkurb)
```

```{r}
dataurb[,c(1,4:7)]=NULL
```

```{r}
dataurb=dataurb[-c(1,3),]
```

```{r}
names(dataurb) = c("Departamento", "Provincia", "Total", "Aurbana", "Arural", "SHombre", "Smujer")
```

```{r}
dataurb=dataurb[-c(1),]
```

```{r}
rownames(dataurb)=NULL
```

```{r}
dataurb[,c(3,6,7)]=NULL
```

INTERNET

```{r}
linkinter="https://github.com/Samanta-Rivera/EPAP2-Proyecto/raw/master/DataInter.xlsx"
datainter=import(linkinter)
```

```{r}
datainter[,c(1,4:7)]=NULL
```

```{r}
names(datainter) = c("Departamento", "Provincia", "Total", "Aurbana", "Arural")
```

```{r}
datainter=datainter[-c(1,3),]
```

```{r}
datainter=datainter[-c(1),]
```

```{r}
rownames(datainter)=NULL
```

```{r}
datainter[,c(1)]=NULL
```

```{r}
datainter[,c(3,4)]=NULL
```

IDH

```{r}
library(rio)
IDH=import("https://github.com/Samanta-Rivera/EPAP2-Proyecto/raw/master/pe.Indice%20de%20Desarrollo%20Humano%20Per%C3%BA%20(2).xlsx")
```

```{r}
IDH[,-c(1,2,3,8)]=NULL
IDH=IDH[c(8:2257),]
names(IDH)=c("Ubigeo",'Region','Provincia','IDH')
IDH$IDH=as.numeric(IDH$IDH)
str(IDH)
```

```{r}
list=as.list(IDH[,1])
provinces=grep(pattern='[0-9]{1}[0-9]{1}[0-9]{1}[0-9]{1}[0]{1}[0]{1}',x=list)
IDH=IDH[c(provinces),]
names(IDH)=c('Ubigeo','Region','Provincia','IDH')
row.names(IDH)=NULL
```

```{r}
IDH$Region[2:8]='Amazonas'
IDH$Region[10:29]='Ancash'
IDH$Region[31:37]='Apurimac'
IDH$Region[39:46]='Arequipa'
IDH$Region[48:58]='Ayacucho'
IDH$Region[60:72]='Cajamarca'
IDH$Region[73]='Callao'
IDH$Region[75:87]='Cusco'
IDH$Region[89:95]='Huancavelica'
IDH$Region[97:107]='Huanuco'
IDH$Region[109:113]='Ica'
IDH$Region[115:123]='Junin'
IDH$Region[125:136]='La Libertad'
IDH$Region[138:140]='Lambayeque'
IDH$Region[142:151]='Lima'
IDH$Region[153:159]='Loreto'
IDH$Region[161:163]='Madre De Dios'
IDH$Region[165:167]='Moquegua'
IDH$Region[169:171]='Pasco'
IDH$Region[173:180]='Piura'
IDH$Region[182:194]='Puno'
IDH$Region[196:205]='San Martin'
IDH$Region[207:210]='Tacna'
IDH$Region[212:214]='Tumbes'
IDH$Region[216:219]='Ucayali'
```

```{r}
IDH=na.omit(IDH)
row.names(IDH)=NULL
```

```{r}
IDH[,c(2)]=gsub('á','a',IDH[,c(2)])
IDH[,c(2)]=gsub('é','e',IDH[,c(2)])
IDH[,c(2)]=gsub('í','i',IDH[,c(2)])
IDH[,c(2)]=gsub('ó','o',IDH[,c(2)])
IDH[,c(2)]=gsub('ú','u',IDH[,c(2)])
IDH[,c(2)]=gsub('ñ','n',IDH[,c(2)])
IDH[,c(2)]=gsub('Á','A',IDH[,c(2)])
IDH[,c(2)]=gsub('É','E',IDH[,c(2)])
IDH[,c(2)]=gsub('Í','I',IDH[,c(2)])
IDH[,c(2)]=gsub('Ó','O',IDH[,c(2)])
IDH[,c(2)]=gsub('Ú','U',IDH[,c(2)])
IDH[,c(2)]=gsub('Ñ','N',IDH[,c(2)])

IDH[,c(3)]=gsub('á','a',IDH[,3])
IDH[,c(3)]=gsub('é','e',IDH[,c(3)])
IDH[,c(3)]=gsub('í','i',IDH[,c(3)])
IDH[,c(3)]=gsub('ó','o',IDH[,c(3)])
IDH[,c(3)]=gsub('ú','u',IDH[,c(3)])
IDH[,c(3)]=gsub('ñ','n',IDH[,c(3)])
IDH[,c(3)]=gsub('Á','A',IDH[,c(3)])
IDH[,c(3)]=gsub('É','E',IDH[,c(3)])
IDH[,c(3)]=gsub('Í','I',IDH[,c(3)])
IDH[,c(3)]=gsub('Ó','O',IDH[,c(3)])
IDH[,c(3)]=gsub('Ú','U',IDH[,c(3)])
IDH[,c(3)]=gsub('Ñ','N',IDH[,c(3)])
```


MERGING
```{r}
library(rio)
```

```{r}
UrbInter=merge(dataurb,datainter,by.x='Provincia', by.y='Provincia')
```

```{r}
IDH=IDH[,-2]

data2007=merge(IDH,UrbInter)
```


```{r}
data2007$Code=paste0(data2007$Departamento,'-',data2007$Provincia)
data2007[,c(1,4)]=NULL
```

```{r}
names(data2007)=c('Ubigeo','IDH','Urban_Pop','Rural_Pop','Internet', "Code")
```

PROCESAMIENTO

```{r}
data2007[,c(2:5)]=lapply(data2007[,c(2:5)],as.numeric)
```

```{r}
data2007$Total_Pop=rowSums(data2007[,c(3,4)])
data2007$Rur_Porc <- data2007$Rural_Pop / data2007$Total_Pop
data2007[,c(3,4)]=NULL
```

```{r}
data2007$ProvCode=data2007$Code
data2007[,c(4,5)]=NULL
```

```{r}
library(rio)
IDH=import("https://github.com/Samanta-Rivera/EPAP2-Proyecto/raw/master/pe.Indice%20de%20Desarrollo%20Humano%20Per%C3%BA%20(2).xlsx")
```

```{r}
library(rio)
IDH=import("https://github.com/Samanta-Rivera/EPAP2-Proyecto/raw/master/pe.Indice%20de%20Desarrollo%20Humano%20Per%C3%BA%20(2).xlsx")
```

```{r}
IDH[,-c(1,2,3,10,12,14,16)]=NULL
IDH=IDH[c(8:2257),]
names(IDH)=c("Ubigeo",'Region','Provincia','EspVid','EduSecComp','AEdu' ,'IngFamppc')
IDH[,c(4:7)]=lapply(IDH[,c(4:7)],as.numeric)
str(IDH)
```

```{r}
list=as.list(IDH[,1])
provinces=grep(pattern='[0-9]{1}[0-9]{1}[0-9]{1}[0-9]{1}[0]{1}[0]{1}',x=list)
IDH=IDH[c(provinces),]
row.names(IDH)=NULL
```

```{r}
IDH$Region[2:8]='Amazonas'
IDH$Region[10:29]='Ancash'
IDH$Region[31:37]='Apurimac'
IDH$Region[39:46]='Arequipa'
IDH$Region[48:58]='Ayacucho'
IDH$Region[60:72]='Cajamarca'
IDH$Region[73]='Callao'
IDH$Region[75:87]='Cusco'
IDH$Region[89:95]='Huancavelica'
IDH$Region[97:107]='Huanuco'
IDH$Region[109:113]='Ica'
IDH$Region[115:123]='Junin'
IDH$Region[125:136]='La Libertad'
IDH$Region[138:140]='Lambayeque'
IDH$Region[142:151]='Lima'
IDH$Region[153:159]='Loreto'
IDH$Region[161:163]='Madre De Dios'
IDH$Region[165:167]='Moquegua'
IDH$Region[169:171]='Pasco'
IDH$Region[173:180]='Piura'
IDH$Region[182:194]='Puno'
IDH$Region[196:205]='San Martin'
IDH$Region[207:210]='Tacna'
IDH$Region[212:214]='Tumbes'
IDH$Region[216:219]='Ucayali'
```

```{r}
IDH=na.omit(IDH)
row.names(IDH)=NULL
```

```{r}
IDH[,c(2)]=gsub('á','a',IDH[,c(2)])
IDH[,c(2)]=gsub('é','e',IDH[,c(2)])
IDH[,c(2)]=gsub('í','i',IDH[,c(2)])
IDH[,c(2)]=gsub('ó','o',IDH[,c(2)])
IDH[,c(2)]=gsub('ú','u',IDH[,c(2)])
IDH[,c(2)]=gsub('ñ','n',IDH[,c(2)])
IDH[,c(2)]=gsub('Á','A',IDH[,c(2)])
IDH[,c(2)]=gsub('É','E',IDH[,c(2)])
IDH[,c(2)]=gsub('Í','I',IDH[,c(2)])
IDH[,c(2)]=gsub('Ó','O',IDH[,c(2)])
IDH[,c(2)]=gsub('Ú','U',IDH[,c(2)])
IDH[,c(2)]=gsub('Ñ','N',IDH[,c(2)])

IDH[,c(3)]=gsub('á','a',IDH[,3])
IDH[,c(3)]=gsub('é','e',IDH[,c(3)])
IDH[,c(3)]=gsub('í','i',IDH[,c(3)])
IDH[,c(3)]=gsub('ó','o',IDH[,c(3)])
IDH[,c(3)]=gsub('ú','u',IDH[,c(3)])
IDH[,c(3)]=gsub('ñ','n',IDH[,c(3)])
IDH[,c(3)]=gsub('Á','A',IDH[,c(3)])
IDH[,c(3)]=gsub('É','E',IDH[,c(3)])
IDH[,c(3)]=gsub('Í','I',IDH[,c(3)])
IDH[,c(3)]=gsub('Ó','O',IDH[,c(3)])
IDH[,c(3)]=gsub('Ú','U',IDH[,c(3)])
IDH[,c(3)]=gsub('Ñ','N',IDH[,c(3)])
```

```{r}
model <- ' NewIDH =~ EduSecComp + AEdu'
model2= "NewIDH2=~ EspVId + IngFamppc"
```

```{r}
IDH[,c(4:7)]=lapply(IDH[,c(4:7)],scale)
```

```{r}
library(lavaan)
library(psych)
library(GPArotation)
cfa_fit <- cfa(model, data=IDH, 
           std.lv=TRUE,  
           missing="fiml")

cfa_fit2 <- cfa(model2, data=IDH, 
           std.lv=TRUE,  
           missing="fiml")

```

```{r}
allParamCFA=parameterEstimates(cfa_fit,standardized = T)
allFitCFA=as.list(fitMeasures(cfa_fit))


allParamCFA2=parameterEstimates(cfa_fit2,standardized = T)
allFitCFA2=as.list(fitMeasures(cfa_fit2))
```

```{r}
allFitCFA[c("chisq", "df", "pvalue")]
```
```{r}
allFitCFA$tli 
```
```{r}
allFitCFA[c('rmsea.ci.lower','rmsea' ,'rmsea.ci.upper')]
```

```{r}
IDH=as.data.frame(cbind(IDH,lavPredict(cfa_fit)))

IDH=as.data.frame(cbind(IDH,lavPredict(cfa_fit2)))
```


modelo 2


